# 2장 분할정복법(divide-and-conquer)
* 빠른정렬
* 쉬트라센 알고리즘
* 큰 정수 곱셈

### numpy 실습(array 만들기)
* 파이썬에는 array자료구조가 없으나, numpy에서는 array자료구조 지원
* array구조는 수학적인 표현처럼 행렬, 행렬 원소를 표시할 수 있다.
* numpy를 줄여 쓰기 위해 import numpy as np 사용

In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]
print(a)
b = np.array(a)
print(b)

[1, 2, 3]
[1 2 3]


In [5]:
c = [[1, 2, 3], [5, 6, 7]]
print(c)
print(c[1][2])
print()
d = np.array(c)
print(d)
print(d[1, 2])
print(d[1][2])

[[1, 2, 3], [5, 6, 7]]
7

[[1 2 3]
 [5 6 7]]
7
7


* @는 numpy의 행렬의 곱셈 operator

In [6]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [2, 5]]
c = np.array(a)
d = np.array(b)
f = c @ d
print(f)

[[ 5 10]
 [11 20]]


* 행렬의 덧셈, 뺄셈 가능

In [7]:
a = [[1, 2], [3, 4]]
b = [[1, 0], [2, 5]]
c = np.array(a)
d = np.array(b)
f = c + d
print(f)
g = c - d
print(g)

[[2 2]
 [5 9]]
[[ 0  2]
 [ 1 -1]]


* 행렬의 초기화

In [10]:
A = [[2 for j in range(3)] for i in range(2)] 
#안쪽은 열(column)의 인덱스, 바깥은 행(row)의 인덱스
print(A)
B = np.array(A)
print(B)

[[2, 2, 2], [2, 2, 2]]
[[2 2 2]
 [2 2 2]]


In [13]:
A = np.array([[i+j for j in range(3)] for i in range(2)])
print(A)

[[0 1 2]
 [1 2 3]]


* 행렬의 병합

In [15]:
a = [[1, 2], [3, 4]]
b = [[6, 7], [8, 9]]
c = np.array(a)
d = np.array(b)
print(np.hstack([c, d])) # horizontal stack
print()
print(np.vstack([c, d])) # vertical stack

[[1 2 6 7]
 [3 4 8 9]]

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


## 빠른정렬 알고리즘

*의사코드

In [ ]:
void quicksort(index low, index high){
    index pivotpoint;
    if(high > low){
        partition(low, high, pivotpoint);
        quicksort(low, pivotpoint-1);
        quicksort(pivotpoint+1, high);
    }
}

## 분할 알고리즘

*의사코드

In [ ]:
void partition(index low, index high, index& pivotpoint){
    index i, h;
    keytype pivotitem;
    pivotitem = S[low]; // pivotitem으로 첫번째 항목을 고른다
    j = low
    for(i = low + 1; i <= high; i++){
        if (S[i] < pivotitem){
            j++;
            exchagne S[i] and S[j]
        }
    }
    pivotpoint = j;
    exchange S[low] and S[pivotpoint];
}

# j: pivotitem보다 작은 그룹의 제일 우측 끝 데이터의 위치
- not stable (같은 수가 있을때, 3-a와 3-b의 위치가 바뀜)

* [실습] 빠른정렬 알고리즘

In [1]:
import random

def quickSort(s, low, high):
    pivotpoint = 0
    if low < high:
        pivotpoint = partition(s, low, high, pivotpoint)
        quickSort(s, low, pivotpoint-1)
        quickSort(s, pivotpoint+1, high)


def partition(s, low, high, pivotpoint):
    pivotitem = s[low]
    j = low
    i = low + 1
    while i <= high:
        if s[i] < pivotitem:
            j += 1
            s[i], s[j] = s[j], s[i]
        i += 1
    pivotpoint = j
    s[low], s[pivotpoint] = s[pivotpoint], s[low]
    return pivotpoint

s = [3, 5, 2, 9, 10, 14, 4, 8]
quickSort(s, 0, 7)
print(s)

[2, 3, 4, 5, 8, 9, 10, 14]


## 쉬트라쎈의 알고리즘

* 의사코드

In [2]:
void strassen (int n, n*n_matrix A, n*n_matrix B, n*n_matrix& C){
    if(n <= 임계점)
        단순한 알고리즘을 사용하여 C = A*B 를 계산;
    else{
        A를 4개의 부분행렬 A11, A12, A21, A22로 분할;
        B를 4개의 부분행렬 B11, B12, B21, B22로 분할;
        쉬트라쏀의 방법을 사용하여 C = A * B를 계산;
        // 되부르는 호출의 예: strassen(n/2, A11+A12, B11+B22, M1)
    }
}

임계점(threshold)란? 두 알고리즘의 효율성이 교차하는 문제의 크기

SyntaxError: invalid syntax (<ipython-input-2-46a36c94c5b4>, line 1)

* [실습] 쉬트라쎈의 알고리즘

In [3]:
import numpy as np
def strassen(n, A, B, C):
    threshold = 2
    A11 = np.array([[A[rows][cols] for cols in range(int(n/2))]\
                  for rows in range(int(n/2))])
    A12 = np.array([[A[rows][cols+int(n/2)] for cols in range(int(n/2))]\
                  for rows in range(int(n/2))])
    A21 = np.array([[A[rows+int(n/2)][cols] for cols in range(int(n/2))]\
                  for rows in range(int(n/2))])
    A22 = np.array([[A[rows+int(n/2)][cols+int(n/2)] for cols in range(int(n/2))]\
                  for rows in range(int(n/2))])
    B11 = np.array([[B[rows][cols] for cols in range(int(n/2))]\
                  for rows in range(int(n/2))])
    B12 = np.array([[B[rows][cols+int(n/2)] for cols in range(int(n/2))]\
                    for rows in range(int(n/2))])
    B21 = np.array([[B[rows+int(n/2)][cols] for cols in range(int(n/2))]\
                    for rows in range(int(n/2))])
    B22 = np.array([[B[rows+int(n/2)][cols+int(n/2)] for cols in range(int(n/2))]\
                    for rows in range(int(n/2))])

    # print(A11, A12, A21, A22, B11, B12, B21, B22, sep='\n') 결과 테스트
    if n <= threshold:
        C = np.array(A) @ np.array(B)
    else:
        M1 = M2 = M3 = M4 = M5 = M6 = M7 = np.array([])
        M1 = strassen(int(n/2), (A11+A22), (B11+B22), M1)
        M2 = strassen(int(n/2), (A21+A22), B11, M2)
        M3 = strassen(int(n/2), A11, (B12-B22), M3)
        M4 = strassen(int(n/2), A22, (B21-B11), M4)
        M5 = strassen(int(n/2), (A11+A12), B22, M5)
        M6 = strassen(int(n/2), (A21-A11), (B11+B12), M6)
        M7 = strassen(int(n/2), (A12-A22), (B21+B22), M7)
        #행렬 병합하기
        C = np.vstack([np.hstack([M1+M4-M5+M7, M3+M5]),\
                       np.hstack([M2+M4, M1+M3-M2+M6])])
    return C

n = 4
A = [[1 for cols in range(n)] for rows in range(n)]
B = [[2 for cols in range(n)] for rows in range(n)]
A = [[1, 2, 0, 2], [3, 1, 0, 0], [0, 1, 1, 2], [2, 0, 2, 0]]
B = [[0, 3, 0, 2], [1, 1, 4, 0], [1, 1, 0, 2], [0, 5, 2, 0]]
C = np.array(A)@np.array(B)
D = [[0 for cols in range(n)]for rows in range(n)]
print('단순한 알고리즘:\n', C)
print()
D = strassen(n, A, B, D)
print('쉬트라쎈 알고리즘:\n', D)

단순한 알고리즘:
 [[ 2 15 12  2]
 [ 1 10  4  6]
 [ 2 12  8  2]
 [ 2  8  0  8]]

쉬트라쎈 알고리즘:
 [[ 2 15 12  2]
 [ 1 10  4  6]
 [ 2 12  8  2]
 [ 2  8  0  8]]
